site_name: Developer eLearning Course
repo_url: https://github.com/YOUR_USERNAME/YOUR_REPO
repo_name: GitHub
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    scheme: slate
    primary: blue
nav:
  - Home: index.md
  - Getting Started: 01-getting-started.md
  - Core Concepts: 02-core-concepts.md
  - REST API: 03-rest-api.md
  - JavaScript: 04-javascript.md
  - JRuby: 05-jruby.md
  - Quizzes: quizzes/sample-quiz.md
plugins:
  - search
  - awesome-pages
  - mkdocs_quiz
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocs-video
  - exclude
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
